### ISSUE TITLE
Failed to initialize workers locally on Chrome but deployed OK on GitHub

### ISSUE THREAD

**Issue by huyen-nguyen** [josephrocca/clip-image-sorter#3]
Hi Joe :)

There is an issue with browsers that I hope you could help me with!

On Chrome, running locally, it failed to load `vips.worker.js` when initializing models but _ran OK_ when deployed to GitHub page.

On Firefox, running locally, it loaded `vips.worker.js` successfully. So I suppose this is an issue with the browser. Firefox does not support File System Access API, so I can only use the reddit image dataset provided. 

--- Details when running locally on Chrome ---

I ran into this error when initializing the models:

> Failed to execute 'importScripts' on 'WorkerGlobalScope': **The script at 'http://localhost:63342/clip-image-sorter/vips/vips.worker.js' failed to load.`**.

<img width="1804" alt="Screenshot 2024-02-08 at 6 35 25 PM" src="https://github.com/josephrocca/clip-image-sorter/assets/22818938/18d4b946-ac48-4c2a-a300-b9218117cf24">

<img width="1804" alt="Screenshot 2024-02-08 at 6 36 43 PM" src="https://github.com/josephrocca/clip-image-sorter/assets/22818938/ad44b4ef-1544-4325-9e6a-d224ecc70a50">

However, the file `vips.worker.js` is indeed available:
<img width="1804" alt="Screenshot 2024-02-08 at 6 36 59 PM" src="https://github.com/josephrocca/clip-image-sorter/assets/22818938/16043338-ec85-487e-ae43-d6e0951e4ab7">

Any help would be greatly appreciated! Thank you :)
Huyen

**Comment by josephrocca** [comment]
Ah, I think the problem here is related to serving at `localhost:63342/clip-image-sorter` instead of just `localhost:63342`. If you start the webserver from within the `clip-image-sorter` folder then it should work. I'm not sure why it doesn't work, since the I think all my imports are relative (though I could be wrong, only skimmed quickly just now. EDIT: oh, js relative imports change if there's a slash at the end of the URL IIRC [or /index.html], so that could be the reason), but I'm guessing it has something to do with the way vips.js internally handles importing the worker/wasm stuff. Please feel free to reopen if serving the folder directly doesn't fix it.

**Comment by huyen-nguyen** [comment]
Thanks for the comment, Joe! However, serving the folder directly doesn't really fix it. I don't seem to have permission to reopen the issue, so I'll leave a comment here in case anyone else has the same problem.

- The issue was from how Chrome works with the WebStorm built-in static web server, listening on `localhost:63342`. Firefox works OK with this server.

- I made it work it by running a Python server (e.g., simple server with port 8000) at the folder `clip-image-sorter`:

    `Python3 -m http.server 8000`

- Serving from `localhost:8000` works OK on Chrome ✅ . When I run the server on the parent folder, `localhost:8000/clip-image-sorter` also works.
